## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "World Folk Stories"
theme = "hugo-story"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
# googleAnalytics = "your-google-analytics-id"


## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = ""
  logo = "images/banner.jpg"
  favicon = true

[Params.social]
  twitter = "https://twitter.com/DesignHenk"
  email = "stories@henkjurriens.nl"
  instagram = "https://instagram.com/design.henk"