## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "World Folk Stories"
theme = "hugo-story"

defaultContentLanguage = 'en'
[languages]
  [languages.nl]
    title = 'Wereld volksverhalen'
    contentDir = 'content/nl'
    weight = 2
     languageName = 'Nederlands'
  [languages.en]
    title = "World Folk Stories"
    weight = 1
     languageName = 'English'
    [languages.en.params]
      linkedin = 'https://linkedin.com/whoever'


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
# googleAnalytics = "your-google-analytics-id"


## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = ""
  logo = "images/banner-cage.png"
  favicon = true

  [Params.social]
  twitter = "https://twitter.com/DesignHenk"
  email = "stories@henkjurriens.nl"
  instagram = "https://instagram.com/DesignHenk"
 